<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S5MMF0I" failures="5" tests="35" name="com.cw.TestCases.ServicesTest" time="882.809" errors="1" timestamp="2022-12-15T14:01:18 IST" skipped="0">
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC05_ClickOnContactUsBtn" time="25.975"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC22_ClickOnSnowflakeTesting" time="9.928"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC24_ClickOnAgileAndDevOpsTestingServices" time="10.727">
    <failure message="expected [https://cogniwize.com/services/testing-services/quality-engineering/agile-and-devops-testing-services/] but found [https://cogniwize.com/services/quality-engineering/agile-and-devops-testing-services/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cogniwize.com/services/testing-services/quality-engineering/agile-and-devops-testing-services/] but found [https://cogniwize.com/services/quality-engineering/agile-and-devops-testing-services/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.cw.TestCases.ServicesTest.TC24_ClickOnAgileAndDevOpsTestingServices(ServicesTest.java:299)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC24_ClickOnAgileAndDevOpsTestingServices -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC27_ClickOnServiceVirtualizationAndDevOps" time="10.299">
    <failure message="expected [https://cogniwize.com/services/testing-services/quality-engineering/service-virtualization-and-devops/] but found [https://cogniwize.com/services/quality-engineering/service-virtualization-and-devops/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cogniwize.com/services/testing-services/quality-engineering/service-virtualization-and-devops/] but found [https://cogniwize.com/services/quality-engineering/service-virtualization-and-devops/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.cw.TestCases.ServicesTest.TC27_ClickOnServiceVirtualizationAndDevOps(ServicesTest.java:326)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC27_ClickOnServiceVirtualizationAndDevOps -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC30_clickOnSalesForce" time="9.948"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC12_ClickOnTestAutomationSolutions" time="16.796"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC10_ClickOnProcessMiningLink" time="16.532"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC23_ClickOnQualityEngg" time="12.266">
    <failure message="expected [https://cogniwize.com/services/testing-services/quality-engineering/] but found [https://cogniwize.com/services/quality-engineering/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cogniwize.com/services/testing-services/quality-engineering/] but found [https://cogniwize.com/services/quality-engineering/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.cw.TestCases.ServicesTest.TC23_ClickOnQualityEngg(ServicesTest.java:290)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC23_ClickOnQualityEngg -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC01_ClickOnServicesTab" time="21.388"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC04_HoverOnContactUsBtn" time="14.326"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC20_ClickOnIOTtestingServices" time="11.804"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC21_ClickOnBigDataAndAnalyticsTesting" time="11.032"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC09_ClickOnAutomationMigrationlink" time="22.389"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC29_clickOnServiceNow" time="16.130"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC31_clickOnTestAdvisory" time="9.619"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC11_services" time="12.944"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC26_ClickOnTestDataManagementServices" time="11.168">
    <failure message="expected [https://cogniwize.com/services/testing-services/quality-engineering/test-data-management-services/] but found [https://cogniwize.com/services/quality-engineering/test-data-management-services/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cogniwize.com/services/testing-services/quality-engineering/test-data-management-services/] but found [https://cogniwize.com/services/quality-engineering/test-data-management-services/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.cw.TestCases.ServicesTest.TC26_ClickOnTestDataManagementServices(ServicesTest.java:317)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC26_ClickOnTestDataManagementServices -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC15_clickOnPerformanceTestingServices" time="11.505"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC33_clickOnSpecializedAdvisory" time="17.075"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC19_ClickOnArtificialIntelligenceINTesting" time="9.368"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC02_ClickOnServicesDropdown" time="15.255"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC32_clickOnTestingCenter" time="15.047"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC16_clickOnSecurityTestingServices" time="13.455"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC34_clickOnCherwellServices" time="14.131"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC13_ClickOnMobileTestingServices" time="10.436"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC06_serviceLink" time="12.342"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="broken" time="393.968">
    <error message="class sun.net.www.protocol.mailto.MailToURLConnection cannot be cast to class java.net.HttpURLConnection (sun.net.www.protocol.mailto.MailToURLConnection and java.net.HttpURLConnection are in module java.base of loader &#039;bootstrap&#039;)" type="java.lang.ClassCastException">
      <![CDATA[java.lang.ClassCastException: class sun.net.www.protocol.mailto.MailToURLConnection cannot be cast to class java.net.HttpURLConnection (sun.net.www.protocol.mailto.MailToURLConnection and java.net.HttpURLConnection are in module java.base of loader 'bootstrap')
at com.cw.commosActions.BaseTest1.Brokenlinks(BaseTest1.java:111)
at com.cw.TestCases.ServicesTest.broken(ServicesTest.java:399)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- broken -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC14_ClickclickOnAPIandWebTestingServices" time="8.684"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC18_ClickOnDigitalAssuranceAndTestingServices" time="9.495"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC03_BookAConsultationLink" time="28.965"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC25_ClickOnPerformanceEngineeringServices" time="10.695">
    <failure message="expected [https://cogniwize.com/services/testing-services/quality-engineering/performance-engineering-services/] but found [https://cogniwize.com/services/quality-engineering/performance-engineering-services/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cogniwize.com/services/testing-services/quality-engineering/performance-engineering-services/] but found [https://cogniwize.com/services/quality-engineering/performance-engineering-services/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.cw.TestCases.ServicesTest.TC25_ClickOnPerformanceEngineeringServices(ServicesTest.java:308)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC25_ClickOnPerformanceEngineeringServices -->
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC17_ClickOnDigitalTestingServices" time="18.580"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC07_ClickOnRPAlink" time="17.887"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC08_ClickOnHyperAutomationlink" time="20.580"/>
  <system-out/>
  <testcase classname="com.cw.TestCases.ServicesTest" name="TC28_clickOnSaasTesting" time="12.070"/>
  <system-out/>
</testsuite> <!-- com.cw.TestCases.ServicesTest -->
